# Created with:
#
# echo ghp_REDACTED | sudo docker login ghcr.io/6j0-org -u evanstucker-hates-2fa --password-stdin
# kubectl create secret generic regcred --from-file=.dockerconfigjson=<(sudo cat /root/.docker/config.json) --type=kubernetes.io/dockerconfigjson
# k get secret regcred -o yaml | yq 'del(.metadata.creationTimestamp,.metadata.namespace,.metadata.resourceVersion,.metadata.uid)'
# k delete secret regcred
#
apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:DXCyO80GnbzZWY3OtsZZi1kGxrLyOSEeUvBvQ6v84DbziyTM9+JhPB4Q5EEwzr/gzHwL8jgzv8HH/atlf9KuJppZg4wMEwBD+4VNDykQS7v7d0RBmaJ1qGz4Js8/bHwWA5NaJJiHgJKHEkUz18qvClbsaUqDD0ti06dORGtO0Vakm2DL0BEFoPS3btJk13GDBy/fD5ry+NUYW2lwI+RUmFc9M5i1KEiFvmZRN74s+Tv74lkjzxK5OtwkWcD11aZ+,iv:RV8TulxkK7BknNlvOltgM9TuBvt+PMoSqRQh3xwl9WU=,tag:B4yuOXVe3Rnd9iLyBLUZlg==,type:str]
kind: Secret
metadata:
    name: regcred
type: kubernetes.io/dockerconfigjson
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:999999999999:key/4aaaaaaa-4518-4aaa-8aaa-aaaaaaaaaaaa
          created_at: "2024-09-24T23:16:11Z"
          enc: AQICAHhnXlyLrjRZY5Xg2fdFsLPNaHKLxDbrBc+XETMpSeQU8wEvhWVA2ZqS5sIs7Yz+hpHTAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMSjh0FAv/0ezPq7BoAgEQgDscDATqGqtu966iXI9Uv/u0vn8GKpFK4WFWdlSVlutrktjrtxE6iSM52rYSGgNbHjhwKmlMUxbrK9kVRg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-09-24T23:16:26Z"
    mac: ENC[AES256_GCM,data:cYdRJOSiQFtxjZV5fhJ06YslwXN2Wo7yt1LrtT+FyfwxJ3xaNn9GpZS78SWZEVoHwE5Q8a/SXi95QZsTZqc+4QEHjMVpTiPNFPShnxfF2M7fhuzCR4dTIlIFdEsoXbPvyh9WXoVrcJOEHHqpWxJdgNb+yYyt6pVu0PnflAiF7iw=,iv:MBCQTXWoOYjifXOj+oziXLlR6G+BdU72YdSWROH6hs4=,tag:mTS508f9nYOh2Pe4tqc1fQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
