ghostPassword: ENC[AES256_GCM,data:MmKumGiJUi89G+6yJu4=,iv:8V1pvE9YN98GWv2P2mH/X2ubM1ipnFLmgqisusSk+Bw=,tag:YiddWF5ygFjflsK5JXx7Kg==,type:str]
mysql:
    auth:
        rootPassword: ENC[AES256_GCM,data:OIEI4xAVpBuk/39Bg+8=,iv:mkvFdbObuPj9t3ywWI0JS5MaUJUmTquN+sf5ydjqDVk=,tag:4ZekDOizk4m4zbkit3TnWQ==,type:str]
        password: ENC[AES256_GCM,data:DVIUv/S2QBTVJHNH25I=,iv:CcvOjcBy8fSSbrP//j9JR6pIxqxum7focxmKpKU9gpA=,tag:87qnHpu2zOAX7EwYQ5jznA==,type:str]
        replicationPassword: ENC[AES256_GCM,data:0IRNuoSqxsFZ7BJdpqU=,iv:ISpn35O7PJRPZD04ZZO/aCZb8rpovz+d+KRNJD6U4hc=,tag:s4ZesBKKL1OaBJ6H3B4rKw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:999999999999:key/4aaaaaaa-4518-4aaa-8aaa-aaaaaaaaaaaa
          created_at: "2024-09-25T18:03:04Z"
          enc: AQICAHhnXlyLrjRZY5Xg2fdFsLPNaHKLxDbrBc+XETMpSeQU8wFa1Pp7GcWvJRbH9rtVZ2OXAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMaT7jx7HuMD5mN1NeAgEQgDuzXLZmPM4AGbLLai+8jWI+VAbygPANcsfW3Fc6VrE0ZZ3zDqzqnlLvAMWuweMucSk81wmiw3eLeTwMvg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-09-25T18:17:10Z"
    mac: ENC[AES256_GCM,data:LFl6rGQnqmKjGNH6yzXGiJs6HTCvxwrHeh6JqJlq2gBJ+Azbho4znMPEDLdyYU2fdYM9CC00iXVh5rKeA6Ve7tMEjmH5eEOA+UcOGfbUYSyL+ey3VYqqmWOmYFJoy3d736pTw3TsNwHg4pMjKaQdJUc2mM9mRK7SqT8xpDNvww8=,iv:8ZykGSZT5/yG5fg9GXj99wD5J5Rs5ZuxVI5a08ehRZY=,tag:jI23RjGeCAxH2VzcKeQASQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
