auth:
    adminPassword: ENC[AES256_GCM,data:uccqNz34e3VKB6MbRKE=,iv:DQmlJcUao8lWYONKOiu6fkuvhRVy44iGUPUE56aGATY=,tag:LmZ+9SL1ewuCCNoRYuJ8fg==,type:str]
externalDatabase:
    #ENC[AES256_GCM,data:kqNj2HL+q51u3YSfuodOhGQ/dZEHJAk0erEef4K05ydk18FlExdokuOkfBCxwwss4EAbKrEK0KrP9CodDUsgpKRGJB51gzVvHCNsZB76DjKkdjAUZgvp9xwOr7uFn7cMPsxkJQ==,iv:gC55/aEMr8eVDZO3VY9tMwemkDPkVYnpMDaUnOeKO4c=,tag:vA2DOUI2bMnDTjehWWi5RQ==,type:comment]
    password: ENC[AES256_GCM,data:73FmG3xWNOk0/cdf470=,iv:aHXPBGb2MiRScXNmFsHuYANfh6XTW1OHCVfRHcGOpEg=,tag:E2ko13TF3z8Er4c4GDYm2w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:999999999999:key/4aaaaaaa-4518-4aaa-8aaa-aaaaaaaaaaaa
          created_at: "2024-09-25T18:17:32Z"
          enc: AQICAHhnXlyLrjRZY5Xg2fdFsLPNaHKLxDbrBc+XETMpSeQU8wFaApYsliT3+jbaGlMOFh6kAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMYpMX5WFDYfDh/lZsAgEQgDuYoW1xWRo5Tn3BwHYo0jwD2SYGaZ1MBS/prgK5prGXsVUuZe13oXmGZe9KUSlzDjWst2P4XWZsHd0/Pg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-09-25T18:18:00Z"
    mac: ENC[AES256_GCM,data:8opEMhfXSREnv5ghllWkQAb/2yAXAkF6P6T1XTNAkiOESMfCQ/IVzOsfoSpAE5Yi1DkWOQv1+pUkauHg4Aqc6ERl3692FvuSHq7a7dOrO1NRXjE3U28Hrs0eDM50ZcKDnvYvUL+WobT/sfpdX37E7rMSSt6FM1f8vmi0d7oc0W8=,iv:1YZJu1yBmMRHT1MWUD8v19D59RdBFC/PqBaItAu/gQk=,tag:xVGgNKVBOQXAMyLCKwAgSQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
