minio:
    rootPassword: ENC[AES256_GCM,data:fJlxjcxz7PjkszihVXE=,iv:IcQ+O+2I7e/DLvC6jJb3YDoYrd7FIelkgYnm/7W9pCE=,tag:Zz7aQQ583+RAVG9gBIHQEw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:999999999999:key/4aaaaaaa-4518-4aaa-8aaa-aaaaaaaaaaaa
          created_at: "2024-09-25T22:05:16Z"
          enc: AQICAHhnXlyLrjRZY5Xg2fdFsLPNaHKLxDbrBc+XETMpSeQU8wHaE6S5mnBSrE6BgDuWBP28AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMjM2PReznG9GNNJ3WAgEQgDsQ/mPwyrzFVFeLebuYVu2kvZ55/PiLqOcJ6LG8YweyHQrqOA0O1boWfk0ipMFqm2V8vAOY966bM2ZB6w==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-09-25T22:05:31Z"
    mac: ENC[AES256_GCM,data:JyjarCl+G1qxD04oOxalFZRHAHsZ+bJ+7I0RlYKivCZNnBDXCb4s1cLn+xGPa2qzSBny+Q7AinM9yuqP85im3JK8ugmxQPCKV5BAwRqjd4FZk+uqZZAKFAGuv29JXKNpTffAAdu5xVXvUQTXGvkwnbYnb7S4H+B3aeJLwxpYqC8=,iv:J8NdT0Hduu5E2jMahIkq8trdhiaUs4V4Uz5juYxtBQc=,tag:QTRUIE1W4Qfv2K3xZQFQVQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
