#ENC[AES256_GCM,data:L+4lEeersjsC,iv:H0GX54grYuY0VRyeQzIG2sfn2Sp4K1pa6VBH7VrPAc8=,tag:y9tLaIn39am/5WzdrijFyQ==,type:comment]
#ENC[AES256_GCM,data:AVDuW/183A==,iv:kCUTK4VFTmAPOT65AvT5TG1cp4lBy+z+iYPrQYAc4pk=,tag:79b52fg26YuA6ArrrcWcxA==,type:comment]
#ENC[AES256_GCM,data:qzbkrAgvfF2uujSHf+NYNXZrKSt8HhW32RFR0YNv+MmAqIG312eFI4iSFDVfkKsMCoIBafIJGcRrXzvQa9nu,iv:+9SgHb7T3rfLnCREdPIs9t6PlG6ih2as+v00WN47bmU=,tag:E1FPOKx/vPiYBVORXsoklQ==,type:comment]
#ENC[AES256_GCM,data:8tN4TFScnj0uonFi+Y1YvIUKELMqKRNyE0M009In+ivBTW23Q/fjKUkS+zxXfjC+CvKNLFNxAUdSdR7R3HYG00/ne3/RNYLBHbuP/Gsc5wcv27fVew==,iv:FhsSRILIKxYfScHEL5d3ywG1EKAMp/dDCRnNGhZ2n4w=,tag:yBPDdiX1KaaarGfkVKPhsQ==,type:comment]
#ENC[AES256_GCM,data:k54kuKI0lV2plDEVsTupv309fEfzM3B1MbAfYWKBll/dHHM=,iv:mkCeEJsTztodwiB2QCw4wy466Q6VAM/AEFXmHV+kQp4=,tag:0Thxb8thEXZW11v894aoIg==,type:comment]
#ENC[AES256_GCM,data:xu6mUZAs5v8yEHn3Fz5a0PJ4mS518A==,iv:jjFWgbZDi+89TiahrZvj7CzuLswsCKEou+uCn6iPZRM=,tag:cctZ+QnB4WCz+VrYcYhSqA==,type:comment]
#ENC[AES256_GCM,data:m3G1HRwl92XhXSCMXhtPIvij4Cd/DriUM5wcXIcvLVYmyttlzWEl1EINZAhg,iv:ISii6miTWDAr2dhdjdENr6cLyaCt9UAnSMkBbAzyl8o=,tag:vlVdESkQR3I96Fu3uOaMTg==,type:comment]
#ENC[AES256_GCM,data:Je9u4NmcFmuLw9D/qXIgt+JXu2mkbOl/qIOjBomLDrISiBZGkmpZjXQnOIs/kPKooxccEzhtHB4KStkPV2RscTOYXSv3Fw==,iv:4boeqSiUO4CRA24yYPfZF82LBpLZgpq2HZdf8+GRl2s=,tag:zyDhmm0BTUqVx/UR2jW3Sw==,type:comment]
#ENC[AES256_GCM,data:aCEoKv0n1oREhGT7zdBG0+nZt9NLUZFrMi/JwaqwhRcXPMtD4I6hzqGxuMAYaCaZhsQFiIxcBzONhEbf,iv:iTDSpODBBcKdgTdT+BBbOzQz9hPk9yMcAX22qXQufN4=,tag:gHiY7zuaiJEkBVxjHENm0Q==,type:comment]
#ENC[AES256_GCM,data:2d0dQMIfXw==,iv:/FoY5qAwEqG66U/BiVLiFwx++CKzjL+ZZq8rS8cBTyY=,tag:lblw6c53VD2TMY/F3WNLFQ==,type:comment]
config:
    clientSecret: ENC[AES256_GCM,data:GKMKl5J7OwKCA/4xJeLfEYAI,iv:6lftzgGXVP4eb4JmCRyNSrkXpE6WTLxpgtDpGRB8278=,tag:9I/6hV66rm8p/s7ttH6yEA==,type:str]
    #ENC[AES256_GCM,data:cfgS0U7DZGDoquyEEnOCHgxvVg==,iv:d5BbePquLQ21wm3C9yx/GCJiPwBldi2QBOIBhHS0p8U=,tag:WGoYlwhicufPQO3Q7HpO1A==,type:comment]
    #ENC[AES256_GCM,data:eBGQVeXOVeGKxRNPFS22h1GhM/l4O1Y7gO4cZcNs4fg8CNMMfidBna0+,iv:VUgZy37WWvLJlL9+noh7hrqxudjOvaapUrtvSnMtP2c=,tag:jyFLiqrW1nqlU3GuAj0ftg==,type:comment]
    #ENC[AES256_GCM,data:fOD//SUZrvg+0kdXeqEaUqUIQER9cVYJq+NajMr7REEQxgk3Zn8NE0WNlzPhcgaeXqHftAwceM1vop+TIRc8ftW6IA==,iv:DqVLE8TxEM0eEDjJRejsJzKi/qripJZheGI5zTtYezc=,tag:61jpk31Ji+e44JdM738IZw==,type:comment]
    cookieSecret: ENC[AES256_GCM,data:wKeAwqJpk/G4AjmrzrRbUYUAR6D6Wie/5IEMJ86yV/PxDRs2tc8gmV+sWYk=,iv:V3Ft8OLjFKczIlrK7WK0y6Iqj4AWQgEcvtxxSXR3dY8=,tag:0mtHlFd88liTpML35hAc9w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:999999999999:key/4aaaaaaa-4518-4aaa-8aaa-aaaaaaaaaaaa
          created_at: "2024-09-25T22:05:45Z"
          enc: AQICAHhnXlyLrjRZY5Xg2fdFsLPNaHKLxDbrBc+XETMpSeQU8wH4llsls0pocAOpCC9wm8XzAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMtVOIiKKmhWr933VbAgEQgDubH6uTiWMYtkyTb4o+WuKTWIqESj28huw+50JqlzcNqOxMO0Gx0tMjkV9Kea7CTGY1Gnw1T/erXqCkPA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-09-25T22:07:43Z"
    mac: ENC[AES256_GCM,data:BDoT6XgNQnBmtjxcmL8bsrdZn83HGneNl2m6snMzm2S27Tu/c47v9TKZto8BQtHUZq5S2iLCVJXlCVukBoBs58KxfL73T0n0krlYNn1RFrm9EDUdNTs9Nb5fDTVjhfgWB9+B0n9G6xzdMvDCnHx9CXFODmKuRLGrN8g54LxO5zQ=,iv:/h9JWAmMIBNDfTDdiuO0LWpdtJCQRi4sTA90Lcfw7Kk=,tag:JJtrdkBvgquAk1G8StuWuQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
