auth:
    password: ENC[AES256_GCM,data:ST7TAvs=,iv:aow+qB0Uc0GPDlfsrUE2e11F+4xJsPHtls35Mjhe0hQ=,tag:MwdPujQEfUJFxfv3pFie1g==,type:str]
    erlangCookie: ENC[AES256_GCM,data:7eN0I5aghqfIgqGpM1nO0Z5cIC6dgOjBnF7xa+jKAG8=,iv:HKhPhApqcwSciPmWx32zhUfeDnCoItcGZOFRstsD8VY=,tag:/kyVrpUhQPm4Lk9N4+u34A==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:999999999999:key/4aaaaaaa-4518-4aaa-8aaa-aaaaaaaaaaaa
          created_at: "2024-09-25T22:08:44Z"
          enc: AQICAHhnXlyLrjRZY5Xg2fdFsLPNaHKLxDbrBc+XETMpSeQU8wHyxto6vdfErulux320vfxqAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMyXJBPnwONPp7EF30AgEQgDtqGmvK+MRVNtpVTPWs4gFaktX9FR5rKPW6VPHWNXMDjtlCNwB4fCOvwSnFGPuZF2apYrsztqZBB76mFA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-09-25T22:09:48Z"
    mac: ENC[AES256_GCM,data:6lKBc8Ea2Oj4z68o/56MGlcNN6/qFAXBxkuTC+HaGIoSJ6xYAapqJTBkTi1uHMOLikadn98uFm2Xz/Z3MdWEHf4L7akQ3KdPB9xjUjWg6HMpwhN/tNiBcBJea50YyMOSzTMd9SmCXek77CrjegKrxLlg1u4lB20B5iss+Uub+9E=,iv:i+pJTjGHCbPr82rKIWjQOILdlFFw1zzGHcwApQXT7fA=,tag:Xsssx6r8Pi96YAKTVK1vjA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
