config:
    vouch:
        jwt:
            secret: ""
    oauth:
        client_secret: ENC[AES256_GCM,data:NaoPMjJVd9H4ShdA5we6hw==,iv:pZ1sfpU8BSIrF61NjJBntJ0O//9J6Pm2PZpcs2Acmb4=,tag:P/eineiNEtnQ31aHu3xv9w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:999999999999:key/4aaaaaaa-4518-4aaa-8aaa-aaaaaaaaaaaa
          created_at: "2024-09-25T22:11:18Z"
          enc: AQICAHhnXlyLrjRZY5Xg2fdFsLPNaHKLxDbrBc+XETMpSeQU8wFTISQt4xH8k+PifmRxpT7tAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMHMZslpjJ2aWvCE1wAgEQgDvyTEqUHVTQ5cD8N3zbnzM5Wmer8AdNzFokiclMt5ZdBZmIiQklzyWttrWvvWRN0KoFnfaMKie36Qs1jA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-09-25T22:11:53Z"
    mac: ENC[AES256_GCM,data:n840WB2YHmm3FcMVOXbxWZ3KuITuKsgNHrxBtpR1IGpTHChu3SUPjMSKWAvgxHaRFoDzCLFLSW7VYadZn7SgGKh7RHA6G2eRCuuQc0Mc3Nqu9u8AJCD4zSCAwJuzhO2OASybzWhsJQa3s7d3FU8bXxxj4MnUlF//6k5NEl/4P9E=,iv:wZn2HiSxde+rMNV3F88DC0ZScD9b/NBXy6/uF/Xv320=,tag:ittXhg5500muCBeLYx1K1w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
